#! /bin/sh

picom -b
feh --bg-fill /home/nahue/Pictures/alps4K.png
xsetroot -cursor_name left_ptr
polybar -r nord &
setxkbmap us
xcape -t 250 -e 'Super_L=Super_L|Shift_R|Meta_L|space'

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config top_monocle_padding -30

bspc rule -a Gnome-calculator state=floating
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Steam desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

light-locker --lock-on-suspend &
sxhkd &
dropbox &
imwheel -k
bluetoothctl power on && sleep 2 && bluetoothctl --timeout 5 connect 04:52:C7:5B:70:1D
