#!/bin/sh

picom -b --experimental-backends
feh --bg-fill /home/nahue/Pictures/alps4K.png
xsetroot -cursor_name left_ptr
killall polybar ; polybar -r nord &
setxkbmap -model pc104 -layout us -variant intl
xcape -t 250 -e 'Super_L=Super_L|Shift_R|Meta_L|space'

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config top_monocle_padding -30

bspc rule -a Gnome-calculator state=floating
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Steam desktop='^4'
bspc rule -a mplayer2 state=floating
#Jedi Fallen Order Origin rule so the game would start automatically
bspc rule -a steam_app_1182480 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config external_rules_command ~/.dotfiles/bspwm/.config/bspwm/external_rules.sh


eval $(keychain --eval --quiet --noask --nogui)
light-locker --lock-on-suspend &
sxhkd &
bluetoothctl power on && sleep 2 && bluetoothctl --timeout 5 connect 78:2B:64:13:DC:47
